import type { Metadata } from "next";
import localFont from "next/font/local";
import { Bungee_Shade } from "next/font/google";
import "./globals.css";

const blMelody = localFont({
  src: [
    { path: "../public/fonts/BLMelody-Book.otf",     weight: "350", style: "normal" },
    { path: "../public/fonts/BLMelody-Regular.otf",  weight: "400", style: "normal" },
    { path: "../public/fonts/BLMelody-Medium.otf",   weight: "500", style: "normal" },
    { path: "../public/fonts/BLMelody-SemiBold.otf", weight: "600", style: "normal" },
  ],
  variable: "--font-bl-melody",
  display: "swap",
});

const bungeeShade = Bungee_Shade({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bungee-shade",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${blMelody.variable} ${bungeeShade.variable}`}>
      <body>{children}</body>
    </html>
  );
}
